### ISSUE TITLE
yeah,one more bug

### ISSUE THREAD

**Issue by ZZPHUB** [WolfChen1996/DesktopPet#2]
if i want shrink my cat ,the program will exit......

**Comment by WolfChen1996** [comment]
Congratulations！You found a bug! 
There is a mistake in line 448: lb1.setGeometry(0,0,petwidth, petheight)
You can solving it by changing it into: self.lb1.setGeometry(0,0,petwidth, petheight)

**Comment by ZZPHUB** [comment]
as you kan see ,wo python is as poor as my English.
